Add useful vs-code settings for standarisation.
DPC-Nordics/dpc-next pull request #10
Opened 2021-12-09 22:29 UTC by GuptaSiddhant

I added a couple of useful extensions and many vs-code setttings that will help produc better and standarised code.

2021-12-09 22:45 UTC, bjornallvin requested changes
Hi @GuptaSiddhant. Thanks for the PR.  I like it.  Although I dont think we should mandate how VSCode should look for everyone.  Theme, colors and icons are personal choices I think, and it will not have any effect of the code produced.  So we need to remove some of the changes I think.

2021-12-09 22:45 UTC, bjornallvin commented on .vscode/settings.json
> +  "editor.fontLigatures": true,
I would remove these

2021-12-09 22:45 UTC, bjornallvin commented on .vscode/settings.json
> +  "material-icon-theme.activeIconPack": "react_redux",
I would remove these

2021-12-10 08:32 UTC, bjornallvin commented
@GuptaSiddhant whats the .devcontainer folder for? Seems to be some local configuration for Docker?

2021-12-10 08:33 UTC, GuptaSiddhant commented on .vscode/extensions.json
> -    "coenraads.bracket-pair-colorizer",
Not needed anymore with VS Code's native (and better) bracket pairing.

2021-12-10 08:37 UTC, GuptaSiddhant commented
> @GuptaSiddhant whats the .devcontainer folder for? Seems to be some local configuration for Docker?

`.devcontainer` allows you to setup a standard docker container for [Github Codespaces](https://github.com/features/codespaces). 

I just added some basic NodeJS setup. We can extend it to do some amazing things like setup whole VS code env on the go and develop using GitHub's servers.

I can remove the config files but keeping them won't affect local development in any way.

2021-12-10 08:44 UTC, bjornallvin commented
I think we should leave those out of the repo until we decide to actually use Codespaces for development fro everyone. To not create confusion.

2021-12-10 13:48 UTC, bjornallvin approved these changes

2021-12-10 13:49 UTC, merged